# Server Configuration
server.port=8080

# MEXC API Configuration
# Use environment variables for sensitive data
mexc.access-key=${MEXC_ACCESS_KEY:default_access_key}
mexc.secret-key=${MEXC_SECRET_KEY:default_secret_key}
mexc.base-url=https://api.mexc.com
mexc.timeout=10000

# OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.christianjaena.crypto_signals=DEBUG
logging.level.org.springframework.web.client=DEBUG
